using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using DevExpress.LookAndFeel;
using DAL;
using BLL;

namespace demo23
{
    public partial class FrmDoanhThu : DevExpress.XtraEditors.XtraForm
    {
        HoaDon_BLL hoadon_bll = new HoaDon_BLL();

        public FrmDoanhThu()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            hoadonTableAdapter1.Fill(dataSetBida1.HOADON);
        }

        private void FrmDoanhThu_Load(object sender, EventArgs e)
        {
            // TODO: This line of code loads data into the 'dataSetBida.HOADON' table. You can move, or remove it, as needed.
            this.hOADONTableAdapter.Fill(this.dataSetBida.HOADON);

            UserLookAndFeel.Default.SetSkinStyle("Office 2010 Blue");
            dataGridViewHD.DataSource = hoadon_bll.loadHoaDon();
            float tonggiatri = 0;
            for (int i = 0; i < dataGridViewHD.Rows.Count; i++)
            {
                tonggiatri += float.Parse(dataGridViewHD.Rows[i].Cells["tien"].Value.ToString());
            }
            txttongtien.Text = tonggiatri.ToString();

            //chartControl1.DataSource = hoadon_bll.loadHoaDon();

        }

        private void dataGridViewHD_SelectionChanged(object sender, EventArgs e)
        {
            string mahd = dataGridViewHD.CurrentRow.Cells["ma"].Value.ToString();
            dataGridViewCTHD.DataSource = hoadon_bll.loadCTHDTheoMaHD(mahd);
        }

        private void btnXem_Click(object sender, EventArgs e)
        {
            DateTime tungay = dateTimePickerTu.Value;
            DateTime denngay = dateTimePickerDen.Value;
            dataGridViewHD.DataSource = hoadon_bll.loadHoaDonTheoNgay(tungay, denngay);
            float tonggiatri = 0;
            for (int i = 0; i < dataGridViewHD.Rows.Count; i++)
            {
                tonggiatri += float.Parse(dataGridViewHD.Rows[i].Cells["tien"].Value.ToString());
            }
            txttongtien.Text = tonggiatri.ToString();
        }
    }
}